syntax on
set nocompatible
set nobackup
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix
set fileencodings=utf-8,cp932,iso2022-jp,euc-jp,sjis,ucs-2
set shiftwidth=4
set tabstop=4
set noexpandtab
set autoindent
set backspace=indent,eol,start
